# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinetask',
            name='task',
            field=models.CharField(max_length=40),
        ),
    ]
