# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:14
from __future__ import unicode_literals

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0002_auto_20160315_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='created_by',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
