# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_auto_20160315_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
